### ISSUE TITLE
about training on Synthetic Denoising

### ISSUE THREAD

**Issue by wam730** [nagejacob/TBSN#3]
Thank you so much for your work! While going through the appendix of your paper, I noticed that you used NLLLoss when training on synthetic noise. I have a couple of questions:
**1) May I ask why you chose to use NLLLoss instead of traditional MSEloss?
2) Could you please let me know which dataset you used for training?**
Thanks！

**Comment by nagejacob** [comment]
1) As illustrated in [HQSSL](https://arxiv.org/abs/1901.10277), training BSN with MSE loss will ignore the corresponding input pixel of each output pixel, while NLL loss could leverage the corresponding input pixel with bayesian posterior inference for better performance.
2) The training data is the same as [this](https://github.com/NVlabs/selfsupervised-denoising)

**Comment by wam730** [comment]
Thank you for your answer! I also have a new question to ask. I have observed that pixel downsampling (PD) is not used in your [method,](https://github.com/nagejacob/TBSN/blob/main/network/tbsn.py#L263) but the general denoising methods applied to real-world noise all need to use PD technology to break the correlation of noise. May I ask how does your method achieve the goal of breaking the correlation of noise?

**Comment by nagejacob** [comment]
For synthetic denoising, pixel-shuffle downsampling (PD) is not needed for training. But for real-world noise, we also use PD to break the noise correlation, as implemented in [here](https://github.com/nagejacob/TBSN/blob/main/model/apbsn.py).
